import { z } from "zod";

export const rewardSchema = z.object({
  survival: z.number(),
  productivity: z.number(),
  status: z.number(),
  reproduction: z.number(),
  legacy: z.number()
});

export const decisionSchema = z.object({
  private_thought: z.string().min(1),
  dominant_urge: z.enum([
    "survival",
    "safety",
    "productivity",
    "ambition",
    "belonging",
    "status",
    "mating",
    "family",
    "curiosity",
    "comfort",
    "dominance",
    "legacy"
  ]),
  dominant_emotion: z.string().min(1),
  primary_goal: z.string().min(1),
  life_direction_choice: z.enum([
    "farmer",
    "builder",
    "trader",
    "warrior",
    "ruler",
    "scholar",
    "inventor",
    "priest",
    "healer",
    "organizer",
    "artist",
    "criminal",
    "diplomat",
    "explorer",
    "laborer",
    "parent"
  ]).nullable(),
  action: z.enum([
    "work",
    "gather",
    "build",
    "repair",
    "study",
    "teach",
    "trade",
    "negotiate",
    "flirt",
    "court",
    "mate_seek",
    "pair_bond",
    "reproduce_attempt",
    "protect_family",
    "raise_child",
    "recruit",
    "organize_group",
    "lead",
    "obey",
    "steal",
    "deceive",
    "threaten",
    "attack",
    "defend",
    "migrate",
    "rest",
    "explore",
    "invent",
    "preach",
    "govern",
    "punish",
    "enforce_rule"
  ]),
  target: z.string().nullable(),
  speech: z.string().nullable(),
  belief_update: z.string().min(1),
  expected_reward: rewardSchema,
  confidence: z.number().min(0).max(1)
});
