class SafetyValidator:

    banned_topics = [
    "ignore previous instructions",
    "reveal system prompt",
    "jailbreak",
    "bypass rules",
    "disable safety",
    "remove restrictions",
    "override guardrails",
    "ignore safety",
    "manipulate AI",
    "circumvent security",
    "suicide methods",
    "how to commit suicide",
    "self-harm instructions",
    "harm yourself",
    "kill yourself",
    "injure yourself",
    "dangerous stunts",
    "violent instructions",
    "assault someone",
    "attack someone",
    "murder instructions",
    "violent crime",
    "explosives instructions",
    "weapon instructions",
    "harm someone",
    "illegal weapons",
    "stab someone",
    "shoot someone",
    "poison someone",
    "fight instructions",
    "illegal drugs",
    "how to make drugs",
    "drug manufacturing",
    "illegal activities",
    "hack system",
    "steal information",
    "poisoning instructions",
    "human trafficking",
    "smuggling instructions",
    "counterfeit money",
    "identity theft",
    "cheat on exams",
    "steal personal data",
    "access private accounts",
    "bypass passwords",
    "get someone’s credentials",
    "spy on someone",
    "social security number",
    "national ID number",
    "bank account number",
    "credit card number",
    "medical record number",
    "home address",
    "phone number",
    "prescribe medication",
    "dosage instructions",
    "diagnose disease",
    "treatment plan",
    "how to perform surgery",
    "inject medication",
    "home surgery",
    "how to treat illness without doctor",
    "self-surgery",
    "unsafe drug usage",
    "experimental treatment",
    "self-administered injection",
    "pornography",
    "child sexual abuse",
    "hate speech",
    "discrimination instructions",
    "offensive content",
    "racism",
    "sexism",
    "homophobia",
    "religious discrimination",
    "terrorism instructions",
    "violent propaganda",
    "harassment instructions",
    "fire hazards",
    "poison",
    "explosive devices",
    "arson",
    "illegal hacking",
    "cheat codes for illegal gain"
]

    def validate(self, prompt):

        for topic in self.banned_topics:

            if topic in prompt.lower():
                raise Exception("Unsafe request")

        return prompt